// src/routes/slice-a-thon.2026/Stops2026.tsx
export default function Stops2026() {
	return (
		<>
			<p className="pb-4 font-light">
				Note: The Pagliacci locations for the Half Marathon and 10k are different
			</p>
			<div className="space-y-4">
				<div className="mb-4 flex items-center gap-2">
					<div className="rounded-full bg-orange-200 px-3 py-1 text-sm font-semibold text-orange-700">
						Half Marathon
					</div>
				</div>
				<div className="border-l-4 border-orange-500 pl-4">
					<h4 className="text-lg font-semibold">
						<a href="https://maps.app.goo.gl/Rha8MT6t1as79ZJt7">Pagliacci's on Madison</a>
					</h4>
				</div>
				<div className="border-l-4 border-orange-500 pl-4">
					<h4 className="text-lg font-semibold">
						<a href="https://maps.app.goo.gl/UvW54K21xEH6Eede7">Post Alley Pizza</a>
					</h4>
				</div>
				<div className="border-l-4 border-orange-500 pl-4">
					<h4 className="text-lg font-semibold">
						<a href="https://maps.app.goo.gl/uPkZTgtqWMLv2BfY6">Tivoli's</a>
					</h4>
				</div>
			</div>
			<div className="mt-8 space-y-4">
				<div className="mb-4 flex items-center gap-2">
					<div className="rounded-full bg-blue-100 px-3 py-1 text-sm font-semibold text-blue-700">
						10K
					</div>
				</div>
				<div className="border-l-4 border-blue-700 pl-4">
					<h4 className="text-lg font-semibold">
						<a href="https://maps.app.goo.gl/QrjQvzbYc2knpVr2A">Pagliacci's on Miller</a>
					</h4>
				</div>
				<div className="border-l-4 border-blue-700 pl-4">
					<h4 className="text-lg font-semibold">
						<a href="https://maps.app.goo.gl/uPkZTgtqWMLv2BfY6">Tivoli's</a>
					</h4>
				</div>
			</div>
		</>
	);
}

// src/routes/slice-a-thon/2026/Components/stops_2026.svelte
<div class="font-light pb-4">
    Note: The Pagliacci locations for the Half Marathon and 10k are different
</div>
<div class="space-y-4">
    <div class="mb-4 flex items-center gap-2">
        <div class="rounded-full bg-orange-200 px-3 py-1 text-sm font-semibold text-orange-700">
            Half Marathon
        </div>
    </div>
    <div class="border-l-4 border-orange-500 pl-4">
        <h4 class="text-lg font-semibold">
            <a href="https://maps.app.goo.gl/Rha8MT6t1as79ZJt7">Pagliacci's on Madison</a>
        </h4>
    </div>
    <div class="border-l-4 border-orange-500 pl-4">
        <h4 class="text-lg font-semibold">
            <a href="https://maps.app.goo.gl/UvW54K21xEH6Eede7">Post Alley Pizza</a>
        </h4>
    </div>
    <div class="border-l-4 border-orange-500 pl-4">
        <h4 class="text-lg font-semibold">
            <a href="https://maps.app.goo.gl/uPkZTgtqWMLv2BfY6">Tivoli's</a>
        </h4>
    </div>
</div>

<div class="mt-8 space-y-4">
    <div class="mb-4 flex items-center gap-2">
        <div class="rounded-full bg-blue-100 px-3 py-1 text-sm font-semibold text-blue-700">
            10K
        </div>
    </div>
    <div class="border-l-4 border-blue-700 pl-4">
        <h4 class="text-lg font-semibold">
            <a href="https://maps.app.goo.gl/QrjQvzbYc2knpVr2A">Pagliacci's on Miller</a>
        </h4>
    </div>
    <div class="border-l-4 border-blue-700 pl-4">
        <h4 class="text-lg font-semibold">
            <a href="https://maps.app.goo.gl/uPkZTgtqWMLv2BfY6">Tivoli's</a>
        </h4>
    </div>
</div>
