// src/routes/slice-a-thon/2026.tsx
import { useState } from 'react';
import { type MetaFunction, Link } from 'react-router';
import {
	CalendarFoldIcon,
	ClockIcon,
	FlagIcon,
	PizzaIcon,
	Ruler
} from 'lucide-react';
import Counter from '~/lib/components/legacy/Counter';
import Registration from '~/lib/components/legacy/Registration';
import Faq2026 from './2026/Faq2026';
import Route2026 from './2026/Route2026';
import Stops2026 from './2026/Stops2026';

export const meta: MetaFunction = () => [
	{ title: 'Seattle Slice-a-Thon 2026' },
	{
		name: 'description',
		content: '10k and half marathon fun run around Seattle stopping by 3 pizza spots'
	}
];

const eventDate = new Date('May 16, 2026 4:00 PM PDT');

const TABS = ['overview', 'route', 'stops', 'faq'] as const;
type Tab = (typeof TABS)[number];
const TAB_LABELS: Record<Tab, string> = {
	overview: 'Overview',
	route: 'Route',
	stops: 'Pizza Stops',
	faq: 'FAQ'
};

export default function SliceAThon2026() {
	const [tab, setTab] = useState<Tab>('overview');

	return (
		<>
			<div className="bg-red-sauce/90 shadow-lg backdrop-blur-sm">
				<Counter judgementDate={eventDate.getTime()} />
			</div>

			<div className="grid grid-cols-1 md:grid-cols-2 md:gap-1 lg:grid-cols-4">
				{[
					{ icon: <CalendarFoldIcon />, label: 'Date', value: 'May 16, 2026' },
					{ icon: <ClockIcon />, label: 'Time', value: '4:00 PM PDT' },
					{ icon: <FlagIcon />, label: 'Location', value: 'Gasworks Park' },
					{
						icon: <Ruler />,
						label: 'Distance',
						value: 'Half Marathon (13.1 miles) and 10km'
					}
				].map(({ icon, label, value }) => (
					<div
						key={label}
						className="glass-strong mx-5 my-1 rounded-2xl border border-black/10 p-3 shadow-md md:m-5"
					>
						<div className="flex items-center gap-2">
							{icon}
							<span className="font-bold">{label}</span>
						</div>
						<div className="mt-2">{value}</div>
					</div>
				))}
			</div>

			<div className="glass-strong mx-5 my-1 max-w-full rounded-2xl border border-black/10 p-3 shadow-md md:m-5">
				<div className="flex items-center gap-2 whitespace-nowrap">
					<PizzaIcon />
					<span className="font-bold">Number of Pizza Stops</span>
				</div>
				<div className="mt-2">3</div>
			</div>

			<div className="mx-5 mt-6 max-w-full">
				<Link to="/donate" target="_blank" rel="noopener" className="block">
					<div className="bg-linear-to-r from-orange-600 to-red-sauce hover:from-orange-600 hover:to-red-sauce flex cursor-pointer flex-col items-center justify-between gap-4 rounded-2xl px-5 py-7 text-white transition-all sm:flex-row">
						<div>
							<p className="text-2xl font-extrabold">Donate to Free2Fly!</p>
							<p className="text-md font-semibold">
								Help visually-impaired athletes in our community
							</p>
						</div>
						<button className="bg-white text-red-sauce rounded-lg p-3 font-semibold">
							Learn More &amp; Donate →
						</button>
					</div>
				</Link>
			</div>

			<div className="mx-5 mt-6 max-w-full">
				<a
					href="https://slice-enterprises.printful.me/"
					target="_blank"
					rel="noopener"
					className="block"
				>
					<div className="bg-linear-to-r from-blue-500 to-blue-900 hover:from-blue-600 hover:to-blue-950 flex cursor-pointer flex-col items-center justify-between gap-4 rounded-2xl px-5 py-7 text-white transition-all sm:flex-row">
						<div>
							<p className="text-2xl font-extrabold">Get your Slice-a-thon Gear!</p>
							<p className="text-md font-semibold">T-shirts, hats, and more now available now</p>
						</div>
						<button className="rounded-lg bg-white p-3 font-semibold text-blue-900">
							Shop merch →
						</button>
					</div>
				</a>
			</div>

			<div className="glass-strong m-3 min-h-[30vh] rounded-2xl border border-black/10 p-3 shadow-md">
				{/* Mobile: select dropdown */}
				<div className="mb-4 sm:hidden">
					<select
						className="bg-surface/80 text-md w-full rounded-lg border p-4 font-semibold shadow-md"
						value={tab}
						onChange={(e) => setTab(e.target.value as Tab)}
					>
						{TABS.map((t) => (
							<option key={t} value={t}>
								{TAB_LABELS[t]}
							</option>
						))}
					</select>
				</div>

				{/* Desktop: tab buttons */}
				<div className="mb-4 hidden gap-6 border-b font-semibold sm:flex">
					{TABS.map((t) => (
						<button
							key={t}
							onClick={() => setTab(t)}
							className={`pb-2 transition-colors ${
								tab === t
									? 'border-red-sauce text-red-sauce border-b-2'
									: 'text-gray-600 hover:text-gray-900'
							}`}
						>
							{TAB_LABELS[t]}
						</button>
					))}
				</div>

				{tab === 'overview' && (
					<div>
						<h1 className="font-bold">The race that started it all, back for seconds</h1>
						<p className="mt-4">
							Slice-a-thon was born out of our love for pizza and running. After a very successful
							innaugural event in 2025, we're back in 2026 with a mix of old and new ideas to make
							the 2nd annual even better. This year we're offering not just a half marathon
							distance, but a 10k option as well making the race open to more people!
						</p>
						<p className="mt-1">
							Runners will stop by 3 pizza spots (2 for the 10k option) for their choice of a
							slice of 'za. Once you return to the finish line, there will be a final slice of pie
							made by our volunteers to round out the race
						</p>
					</div>
				)}
				{tab === 'route' && <Route2026 />}
				{tab === 'stops' && <Stops2026 />}
				{tab === 'faq' && <Faq2026 />}
			</div>

			<div className="glass-strong m-3 flex min-h-[30vh] flex-col items-center rounded-2xl border border-black/10 p-3 shadow-md">
				<div className="w-full lg:w-3xl">
					<Registration iframeId="JotFormIFrame-260540870713151">
						<iframe
							id="JotFormIFrame-260540870713151"
							title="2026 Slice-A-Thon Registration"
							allowTransparency
							src="https://form.jotform.com/260540870713151"
							frameBorder="0"
							style={{ minWidth: '100%', maxWidth: '100%', border: 'none' }}
							scrolling="no"
							width="100%"
						/>
					</Registration>
				</div>
			</div>
		</>
	);
}

// src/routes/slice-a-thon/2026/+page.svelte
<script lang="ts">
	import Counter from '$lib/components/legacy/Counter.svelte';
	import Registration from '$lib/components/legacy/Registration.svelte';
	import {
		AlertCircleIcon,
		CalendarFoldIcon,
		FlagIcon,
		PizzaIcon,
		RulerDimensionLineIcon
	} from '@lucide/svelte';
	import { Tabs } from '@skeletonlabs/skeleton-svelte';
	const eventDate = new Date('May 16, 2026 4:00 PM PDT');
	let tabValue = 'overview';
</script>

<svelte:head>
	<title>Seattle Slice-a-Thon 2026</title>
	<meta
		name="description"
		content="10k and half marathon fun run around Seattle stopping by 3 pizza spots"
	/>
</svelte:head>

<div class="bg-red-sauce/90 shadow-lg backdrop-blur-sm"><Counter judgementDate={eventDate} /></div>

<div class="grid grid-cols-1 md:grid-cols-2 md:gap-8 lg:grid-cols-4">
	<div class="glass-strong mx-5 my-1 h-20 rounded-2xl border border-black/10 p-3 shadow-md md:m-5">
		<div class="flex items-center gap-2">
			<CalendarFoldIcon />
			<span class="font-bold">Date</span>
		</div>
		<div class="mt-2">May 16, 2026</div>
	</div>
	<div class="glass-strong mx-5 my-1 h-20 rounded-2xl border border-black/10 p-3 shadow-md md:m-5">
		<div class="flex items-center gap-2">
			<FlagIcon />
			<span class="font-bold">Location</span>
		</div>
		<div class="mt-2">Gasworks Park</div>
	</div>
	<div class="glass-strong mx-5 my-1 h-20 rounded-2xl border border-black/10 p-3 shadow-md md:m-5">
		<div class="flex items-center gap-2">
			<RulerDimensionLineIcon />
			<span class="font-bold">Distance</span>
		</div>
		<div class="mt-2">Half Marathon (13.1 miles) and 10km</div>
	</div>
	<div class="glass-strong mx-5 my-1 h-20 rounded-2xl border border-black/10 p-3 shadow-md md:m-5">
		<div class="flex items-center gap-2">
			<PizzaIcon />
			<span class="font-bold">Number of Pizza Stops</span>
		</div>
		<div class="mt-2 flex justify-center">3</div>
	</div>
</div>

<div class="glass-strong m-3 min-h-[30vh] rounded-2xl border border-black/10 p-3 shadow-md">
	<Tabs
		value={tabValue}
		onValueChange={(details) => (tabValue = details.value)}
		class="flex flex-col"
	>
		<div class="mb-4 sm:hidden">
			<select
				class="bg-surface/80 text-md w-full rounded-lg border p-4 font-semibold shadow-md"
				bind:value={tabValue}
			>
				<option value="overview">Overview</option>
				<option value="route">Route</option>
				<option value="stops">Pizza Stops</option>
				<option value="faq">FAQ</option>
			</select>
		</div>
		<Tabs.List class="hidden font-semibold sm:flex md:gap-10">
			<Tabs.Trigger value="overview">Overview</Tabs.Trigger>
			<Tabs.Trigger value="route">Route</Tabs.Trigger>
			<Tabs.Trigger value="stops">Pizza Stops</Tabs.Trigger>
			<Tabs.Trigger value="faq">FAQ</Tabs.Trigger>
			<Tabs.Indicator />
		</Tabs.List>
		<Tabs.Content value="overview">
			<div>
				<h1 class="font-bold">The race that started it all, back for seconds</h1>
				<p class="mt-4">
					Slice-a-thon was born out of our love for pizza and running. After a very successful
					innaugural event in 2025, we're back in 2026 with a mix of old and new ideas to make the
					2nd annual even better. This year we're offering not just a half marathon distance, but a
					10k option as well making the race open to more people!
				</p>
				<p class="mt-1">
					Runners will stop by 3 pizza spots (2 for the 10k option) for their choice of a slice of
					'za. Once you return to the finish line, there will be a final slice of pie made by our
					volunteers to round out the race
				</p>
			</div>
		</Tabs.Content>
		<Tabs.Content value="route">
			<div class="grid grid-cols-1 sm:grid-cols-2 md:gap-8">
				<div class="text-center font-bold sm:p-4">
					<h1 class="text-lg">Half Marathon Route</h1>
					<div class="text-red-sauce flex gap-2">
						<AlertCircleIcon />
						<p>Route subject to change</p>
					</div>
					<div
						class="strava-embed-placeholder"
						data-embed-type="route"
						data-embed-id="3445596670059233086"
						data-full-width="true"
						data-style="standard"
						data-map-hash="11.08/47.6303/-122.3272"
						data-from-embed="true"
					></div>
				</div>
				<div class="text-center font-bold sm:p-4">
					<h1 class="text-lg">10k Route</h1>
					<div class="text-red-sauce flex gap-2">
						<AlertCircleIcon />
						<p class="text-red-sauce">Route subject to change</p>
					</div>
					<div
						class="strava-embed-placeholder"
						data-embed-type="route"
						data-embed-id="3460125985862464372"
						data-full-width="true"
						data-style="standard"
						data-map-hash="11.3/47.6276/-122.3427"
						data-from-embed="true"
					></div>
					<script src="https://strava-embeds.com/embed.js"></script>
				</div>
			</div>
		</Tabs.Content>
		<Tabs.Content value="stops">Stops go here</Tabs.Content>
		<Tabs.Content value="faq">FAQ goes here</Tabs.Content>
	</Tabs>
</div>
<div class="glass-strong m-3 min-h-[30vh] rounded-2xl border border-black/10 p-3 shadow-md">
	<Registration iframeId={'JotFormIFrame-260540870713151'}>
		<iframe
			id="JotFormIFrame-260540870713151"
			title="2026 Slice-A-Thon Registration"
			allowtransparency
			src="https://form.jotform.com/260540870713151"
			frameborder="0"
			style="min-width:100%;max-width:100%;border:none;"
			scrolling="no"
			width="100%"
		>
		</iframe>
	</Registration>
</div>
